---
title: "IPM_analyses"
author: "Caroline Rodriguez"
date: "6/7/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = FALSE)
```

```{r}
## Loading libraries
library(ggplot2)
library(patchwork)
library(scales)
library(RColorBrewer)
library(plyr)
library(dplyr)
library(tidyr)
library(reshape2)
library(stringr)
library(lubridate)

```

```{r}
#Maximum likelihood regression
SmithsonVerkuilen2006=function(yi){
  n=length(yi)
  yo=(yi * (n-1) + 0.5) / n
  return(yo)
}
Inv.SmithsonVerkuilen2006=function(yo){
  n=length(yo)
  yi=(n*yo - 0.5)/(n-1)
  return(yi)
}

load("data/Colony_Data_20210917_edited.rdata") #load to update ColonyLevel (41 variables, incl log_10Esc)
load("data/ObservedSFMRecruitment_by_Site_Interval_Genus.rdata")
# ggplot(ColonyLevel, aes(x=log10_ES))+
#   geom_histogram()+
#   facet_wrap("TransitionTypeSimple")+
#   theme_bw()

```

Run This!
```{r BasicIPMsFunctions,}
options(stringsAsFactors=FALSE)

# Global mesh variables 

#min.size <- 0.9*min(c(ColonyLevel$log10_SS, ColonyLevel$log10_ES), na.rm = T)
max.size <- 1.1*max(c(log10(ColonyLevel$StartingSize), log10(ColonyLevel$EndingSize)), na.rm = T)
# max ~ 3.75 m colony diameter
n = 50 #mesh size / number of cells in the discretized kernel
rec.size <- -0.1  # 2*sqrt((10^-0.1)/pi)  # approx 1 cm  diameter coral #2*sqrt((10^1.29303)/pi)  # approx 5 cm  diameter coral
#max.size <- 2     # 2*sqrt((10^2)/pi)     # approx 11 m diameter coral (ridiculous, but avoids boundary issues)
min.size <- -0.5   # 2*sqrt((10^-2.5)/pi)  # approx 6 cm  diameter coral
bin_size <- min.size + c(0:n) * (max.size - min.size)/n #boundary points (the edges of the cells defining the kernel 
y <- 0.5 * (bin_size[1:n]+bin_size[2:(n+1)]) #mesh points (midpoints of cells)
I <- y >= rec.size
delta_size <- y[2] - y[1] #width of cells (h)

inv.logit <- function(x) {
  exp(x)/(1+exp(x))
}

################################################################################
###### The growth model ########################################################
################################################################################

growth_function <- function(y, x, g.int, g.slp, g.var) {
  mu <- (g.int + g.slp * x)
  sig <- sqrt(g.var)
  dnorm(y, mean=mu, sd=sig)
}

################################################################################
###### The survival model ######################################################
################################################################################


survival_function <- function(x, s.int, s.slp,interval_years) {
  #, s.int, s.slp)
  Line <- s.slp * x + s.int
  u <- inv.logit(Line)#^(1/interval_years) # From binomial glm, link = logit function
  return(u)
}

################################################################################
###### The reproduction model ##################################################
################################################################################

reproduction_function <- function(y, x, rec, rec.size=rec.size,ind = FALSE) {
  # 2*sqrt((10^-2.5)/pi)  # approx 6 cm  diameter coral
  if (ind == TRUE){
    out <- rep(0,length(x)) #changed
    out[1:4] <- rec/4} #changed
  
  #out[x < rec.size | y >= rec.size] <- 0}
  
  if (ind == FALSE){
    out <-  (10^x) * rec
    out[x < rec.size | y >= rec.size] <- 0 #if x is below recruitment size then it doesn't count 
  }
  return(out)
}


reproduction_function_josh <- function(y, x,rec, rec.size=rec.size) {
  out <-  (10^x) * rec
  out[x < rec.size | y >= rec.size] <- 0
  return(out)
}

################################################################################
########## ... Running the IPM ... #############################################
################################################################################

bigmatrix <- function(ModelParameters) {
  rec <- ModelParameters$rec
  rec.size <- ModelParameters$rec.size
  g.int <- ModelParameters$g.int
  g.slp <- ModelParameters$g.slp
  g.var <- ModelParameters$g.var
  s.int <- ModelParameters$s.int
  s.slp <- ModelParameters$s.slp
  #iy<- ModelParameters$Interval_Years
  
  #Reproduction_kernel <- delta_size * outer(y, y, 
  #reproduction_function, rec)
  Reproduction_kernel <- delta_size * outer(y, y, 
                                            reproduction_function_josh,rec=rec, 
                                      rec.size=rec.size)
  
  Growth_kernel <- delta_size * outer(y, y, growth_function, g.int=g.int, 
                                      g.slp=g.slp, g.var=g.var)
  ## Growth Kernel
  # only works inside the function or if you have done this by had
  #image(y,y,t(Growth_kernel))
  
  Survival_kernel <- survival_function(y, s.int=s.int, s.slp=s.slp)#,interval_years = iy)

  P <- Growth_kernel
  i <- 1:n
  
  P[,i] <- Growth_kernel[,i]*Survival_kernel[i]
  
  K <- P + Reproduction_kernel
  
  lam <- Re(eigen(K)$values[1])
  w <- Re(eigen(K)$vectors[,1])
  stabledist <- w/sum(w) # right eigenvector/stable distribution
  v.eigen <- Re(eigen(t(K))$vectors[,1]) #left eigenvector
  reprodvalue <- v.eigen/v.eigen[1] #reproductive value
  
  #compute sensitivity and elasticity matrices using the eigenvectors and eigenvalue
  v.dot.w <- sum(stabledist * reprodvalue) * delta_size
  sens <- outer(reprodvalue,stabledist) / v.dot.w
  elas <- matrix(as.vector(sens) * as.vector(K) / lam, nrow = n)
  
  return(list(K=K, Gk=Growth_kernel,Sk=Survival_kernel,Pk=P,lam=lam, w=stabledist, v=reprodvalue,
              v.dot.w=v.dot.w, sens=sens, elas=elas))
}

########################################################################
Scenario="All" # "BadLambda" # "GoodLambda" # 
########################################################################

if(Scenario=="All"){
  all_load_list=load("./data/SiteInterval_All_20210915_allmodfits_noNAs.rdata")
}

#Add Interval Years to each Interval Year!
CLiy=unique(ColonyLevel[,c("Site","Interval","Genus_Code","Interval_Years")])
#prep both data.frames for a left join
names(CLiy)=c("Sites","Years","Genus_Code","Interval_Years")
names(data)[which(names(data)=="AIC")]=c("g.AIC","s.AIC")

#Checking that we only want to keep Interval Years with more than N>MinTrans colonies
#Find low representation intervals to drop
minTrans <- 20 
tCL=table(ColonyLevel[,c("Interval","Interval_Years","Site","Genus_Code")]) #Looks at every interval_years/every time interval & counts # of colonies
for(i in 1:nrow(CLiy)){
  CLiy$NCol[i]=tCL[which(dimnames(tCL)$Interval==CLiy$Years[i]),
                which(dimnames(tCL)$Interval_Years==CLiy$Interval_Years[i]),
                which(dimnames(tCL)$Site==CLiy$Sites[i]),
                which(dimnames(tCL)$Genus_Code==CLiy$Genus_Code[i])]
}


#Join them up (any IntervalYears with sufficient colonies (>MinTrans))
diy=left_join(data,CLiy)

#drop an extra rows with poor representation...
data=diy[which(diy$NCol>minTrans),]



b<- year(SIG_withSFMRec$StartingDate)
#Match data with Recruitment Values
SIG_withSFMRec$Years=paste0(substr(year(SIG_withSFMRec$StartingDate),3,4),"-",
                            substr(year(SIG_withSFMRec$EndingDate),3,4))
left_join(data,SIG_withSFMRec,by=c("Sites"="Site","Years","Genus_Code"))

#[which(table(CLiy)>1,arr.ind=T)]
# dim(data)
# dim(diy)
# dim(diy[which(diy$NCol>minTrans),])
# diy.=diy[which(diy$NCol>minTrans),]
# data.=data[4:nrow(data),]
# diy.[order(diy.$Sites,diy.$Years,diy.$Genus_Code),c("Sites","Years","Genus_Code")]==
#   data.[order(data.$Sites,data.$Years,data.$Genus_Code),c("Sites","Years","Genus_Code")]
# 
# max(table(unique(diy[which(diy$NCol>0),c("Sites","Years","Genus_Code")])))

#Problem with MAI_SIO_OL3 - different interval lengths - I'll drop low representation intervals

data[data == -Inf] <-NA
POCS <- na.omit(data[data$Genus_Code == "POCS",])
POSP <- na.omit(data[data$Genus_Code == "POSP",]) 
MOSP <- na.omit(data[data$Genus_Code == "MOSP",])

```

```{r CalculatingRecVals,}
# Run this and change the recruitment values until you get a value for each Genera that returns a lambda of 1.000__ (we don't care about the values in the digits after the three zeros)

#observed mean beta function estimates
#        POCS        POSP        MOSP 
# 0.004912387 0.005647491 0.004593129 
if(Scenario=="All"){
  recvalpc <- 0.004912387#0.0567 #0.32599 for lambda 1 #mean Beta Function estimate:
  recvalpp <- 0.005647491#0.0732 #2.229822 for lambda 1 
  recvalmp <- 0.004593129#0.1065 #0.1669464 for lambda 1 
}else if (Scenario=="No2015"){
  recvalpc <- 35.75 
  recvalpp <- 29.1  
  recvalmp <- 31.35 
}else if (Scenario=="Yes2015"){
  recvalpc <- 36.07 
  recvalpp <- 34.20 
  recvalmp <- 32.65
}else{
  #   #excl 2015 #28.55 incl all intervals
  #   #excl 2015#24.85 incl all intervals
  #  #excl 2015 #25.25 incl all intervals
  # #q50 of REA
  # recvalpc <- 169.5  #excl 2015 #28.55 incl all intervals
  # recvalpp <- 37.66  #excl 2015#24.85 incl all intervals
  # recvalmp <- 244.8  #excl 2015 #25.25 incl all intervals
}
# 
# # #Speedy rec fitter
# rec_i=seq(0.32598,0.325999,length.out = 1000)
# lam=rep(NA,100)
# for(i in 1:length(rec_i)){rec=rec_i[i];lam[i]=bigmatrix(MP_POCS)$lam}
# rec_i[which.min(abs(lam-1))]

#run all models in "data" with standardized recruitment
recLU=c(recvalpc,recvalpp,recvalmp);names(recLU)=c("POCS","POSP","MOSP")

# data2lam_as=function(data){
#   lamvec=NULL
#   for(i in 1:nrow(data)){
#     MP=list(rec = recLU[data$Genus_Code[i]], 
#                 g.int = data$g.int[i], 
#                 g.slp = data$g.slp[i], 
#                 g.var = data$g.var[i], 
#                 s.int = data$s.int[i], 
#                 s.slp = data$s.slp[i],
#                 Interval_Years=data$Interval_Years[i])
#     thismod=bigmatrix_anns(MP)
#     lamvec=c(lamvec,thismod$lam)
#   }
#   return(lamvec)
# }

data2lam_Xs=function(data){
  lamvec=NULL
  for(i in 1:nrow(data)){
    MP=list(rec = recLU[data$Genus_Code[i]],
                rec.size = rec.size,
                g.int = data$g.int[i], 
                g.slp = data$g.slp[i], 
                g.var = data$g.var[i], 
                s.int = data$s.int[i], 
                s.slp = data$s.slp[i])
                #Interval_Years=data$Interval_Years[i])
    thismod=bigmatrix(MP)
    lamvec=c(lamvec,thismod$lam)
  }
  return(lamvec)
}
data$lambda_ann=data2lam_Xs(data)
#data$lambda_ann=data2lam_as(data)
data$ISL=substring(data$Sites,1,3)
data$StYR=as.numeric(substring(data$Years,1,2))
data$EdYR=as.numeric(substring(data$Years,4,5))

ggplot(data)+
  geom_segment(aes(x=StYR,xend=EdYR,y=lambda_ann,yend=lambda_ann),color="blue")+
  geom_hline(yintercept = 1)+
  facet_grid(ISL~Genus_Code)+
  theme(axis.text=element_text(angle=90))+theme_bw()+xlim(c(13,20))

#Calculate lambda for the regional model (all sites/all years) with a constant recruitment value (recval)
i <- 1
MP_POCS <- list(rec = recvalpc, 
                rec.size = rec.size,
                g.int = POCS$g.int[i], 
                g.slp = POCS$g.slp[i], 
                g.var = POCS$g.var[i], 
                s.int = POCS$s.int[i], 
                s.slp = POCS$s.slp[i],
                interval_years=POCS$Interval_Years[i]
)
pocs <- bigmatrix(MP_POCS)
print(pocs$lam)

MP_POSP <- list(rec = recvalpp, 
                rec.size = rec.size,
                g.int = POSP$g.int[i], 
                g.slp = POSP$g.slp[i], 
                g.var = POSP$g.var[i], 
                s.int = POSP$s.int[i], 
                s.slp = POSP$s.slp[i],
                interval_years=POSP$Interval_Years[i])
posp        <- bigmatrix(MP_POSP)  
print(posp$lam)
# pospas        <- bigmatrix_anns(MP_POSP)  
# print(pospas$lam)

MP_MOSP <- list(rec = recvalmp, 
                rec.size = rec.size,
                g.int = MOSP$g.int[i], 
                g.slp = MOSP$g.slp[i], 
                g.var = MOSP$g.var[i], 
                s.int = MOSP$s.int[i], 
                s.slp = MOSP$s.slp[i],
                interval_years=MOSP$Interval_Years[i])
mosp        <- bigmatrix(MP_MOSP)
print(mosp$lam)

hist(subset(ColonyLevel,Genus_Code=="POCS")$log10_ESc)
hist(subset(ColonyLevel,Genus_Code=="POSP")$log10_ESc)
hist(subset(ColonyLevel,Genus_Code=="MOSP")$log10_ESc)

# Continue on to next chunk to use the stable size distribution to tune the rec value
# Then continue onto the next chunk to calculate the change in lambdas at the different site/intervals
```

```{r RecFromSizeStructure}

# JOSH START
# tune rec to get lambda=1
rec.lam <- function(x) {
  rec <<- x[1]
  mod <- bigmatrix(MP)
  del_lam=abs(1-mod$lam)
  
  return(del_lam) # difference of resulting lambda from 1
}
# SUMS OF SQUARES
#trying to edit function to match data2lam_Xs function but failing
rec.ss <- function(data) {
  #lamvec.ss=NULL
  for (s in 1:nrow(data)) {
    MP=list(n=n,
            ds = delta_size,
            y = y,
+           rec = data[1],
+           rec.size = rec.size,
+           g.int = data$g.int[s], 
+           g.slp = data$g.slp[s], 
+           g.var = data$g.var[s], 
+           s.int = data$s.int[s], 
+           s.slp = data$s.slp[s],
+           Interval_Years=data$Interval_Years[s])
    mod <- bigmatrix(MP)
    eig.vec <- mod$w[I]/sum(mod$w[II])
    cnt <- size.dist$density[II]/sum(size.dist$density[II])
  }
  return(sum((cnt - eig.vec)^2)) # sums of squares
}



#ORIGINAL sum of squares function
rec.ss <- function(x) {
  rec <<- x[1]
  mod <- bigmatrix(MP)
  eig.vec <- mod$w[I]/sum(mod$w[II])
  cnt <- size.dist$density[II]/sum(size.dist$density[II])
  
  return(sum((cnt - eig.vec)^2)) # sums of squares
}






# LOG-LIKELIHOOD
rec.ll <- function(x) {
  rec <<- x[1]
  mod <- bigmatrix(MP)
  eig.vec <- mod$w[II]/sum(mod$w[II])
  cnt <- size.dist$count[II]
  
  return(-sum(cnt * log(eig.vec))) # log-likelihood
}

#II <- I
#Figure out what size classes to include
IIall <- rep(TRUE,length(I))
IInorec <- I
IIad <- I
IImid <- I
IIbig <- I
IIad[1:16] <- FALSE
IImid[1:20] <- FALSE
IIbig[1:25] <- FALSE
II=IIad

#par(mfrow=c(3, 1))
#par(mfrow=c(3, 3))
# POCS
pocs_sizes <- ColonyLevel$log10_SS[ColonyLevel$Genus_Code=="POCS"]
pocs_sizes <- pocs_sizes[!is.na(pocs_sizes) & pocs_sizes != "-Inf"]
pocs_sizes <- pocs_sizes[pocs_sizes < max.size & pocs_sizes > min.size]
#size.dist <- hist(pocs_sizes, breaks=bin_size, freq=FALSE,plot=F)
MP <- MP_POCS

#recval_pocs.lam <- optimize(rec.lam, c(0, 5))$minimum
recval_pocs.lam <- optimize(rec.lam, c(0, 5))$minimum
recval_pocs.ss <- optimize(rec.ss, c(0, 5))$minimum
recval_pocs.ll <- optimize(rec.ll, c(0, 5))$minimum

rec=recval_pocs.lam
mod <- bigmatrix(PARAMS)
hist(pocs_sizes[pocs_sizes > y[II][1]], breaks=bin_size, freq=FALSE,main=paste0("POCS: Lambda = 1; rec = ",round(recval_pocs.lam,4)))
lines(y[II], mod$w[II] / sum(mod$w[II]) / delta_size)
text(4, .25, paste0("lambda=", round(mod$lam, 3)))

rec=recval_pocs.ss
mod <- bigmatrix(PARAMS)
hist(pocs_sizes[pocs_sizes > y[II][1]], breaks=bin_size, freq=FALSE,main=paste0("POCS: W SumSq; rec = ",round(recval_pocs.ss,4)))
lines(y[II], mod$w[II] / sum(mod$w[II]) / delta_size)
text(4, .25, paste0("lambda=", round(mod$lam, 3)))

rec=recval_pocs.ll
mod <- bigmatrix(PARAMS)
png(filename = "Figures/StableSizeDistTuning_POCS.png")
hist(pocs_sizes[pocs_sizes > y[II][1]], breaks=bin_size, freq=FALSE,main=paste0("POCS: W LogLik; rec = ",round(recval_pocs.ll,4)))
lines(y[II], mod$w[II] / sum(mod$w[II]) / delta_size)
text(4, .25, paste0("lambda=", round(mod$lam, 3)))
dev.off()


# POSP
posp_sizes <- ColonyLevel$log10_SS[ColonyLevel$Genus_Code=="POSP"]
posp_sizes <- posp_sizes[!is.na(posp_sizes) & posp_sizes != "-Inf"]
posp_sizes <- posp_sizes[posp_sizes < max.size & posp_sizes > min.size]
PARAMS <- MP_POSP

recval_posp.lam <- optimize(rec.lam, c(0, 5))$minimum
recval_posp.ss <- optimize(rec.ss, c(0, 5))$minimum
recval_posp.ll <- optimize(rec.ll, c(0, 5))$minimum

rec=recval_posp.lam
mod <- bigmatrix(PARAMS)
hist(posp_sizes[posp_sizes > y[II][1]], breaks=bin_size, freq=FALSE,main=paste0("POSP: Lambda = 1; rec = ",round(recval_posp.lam,4)))
lines(y[II], mod$w[II] / sum(mod$w[II]) / delta_size)
text(4, .25, paste0("lambda=", round(mod$lam, 3)))

rec=recval_posp.ss
mod <- bigmatrix(PARAMS)
hist(posp_sizes[posp_sizes > y[II][1]], breaks=bin_size, freq=FALSE,main=paste0("POSP: W SumSq; rec = ",round(recval_posp.ss,4)))
lines(y[II], mod$w[II] / sum(mod$w[II]) / delta_size)
text(4, .25, paste0("lambda=", round(mod$lam, 3)))

rec=recval_posp.ll
mod <- bigmatrix(PARAMS)
png(filename = "Figures/StableSizeDistTuning_POSP.png")
hist(posp_sizes[posp_sizes > y[II][1]], breaks=bin_size, freq=FALSE,main=paste0("POSP: W LogLik; rec = ",round(recval_posp.ll,4)))
lines(y[II], mod$w[II] / sum(mod$w[II]) / delta_size)
text(4, .25, paste0("lambda=", round(mod$lam, 3)))
dev.off()

# MOSP
mosp_sizes <- ColonyLevel$log10_SS[ColonyLevel$Genus_Code=="MOSP"]
mosp_sizes <- mosp_sizes[!is.na(mosp_sizes) & mosp_sizes != "-Inf"]
mosp_sizes <- mosp_sizes[mosp_sizes < max.size & mosp_sizes > min.size]
PARAMS <- MP_MOSP

recval_mosp.lam <- optimize(rec.lam, c(0, 5))$minimum
recval_mosp.ss <- optimize(rec.ss, c(0, 5))$minimum
recval_mosp.ll <- optimize(rec.ll, c(0, 5))$minimum

rec=recval_mosp.lam
mod <- bigmatrix(PARAMS)
hist(mosp_sizes[mosp_sizes > y[II][1]], breaks=bin_size, freq=FALSE,main=paste0("MOSP: Lambda = 1; rec = ",round(recval_mosp.lam,4)))
lines(y[II], mod$w[II] / sum(mod$w[II]) / delta_size)
text(4, .25, paste0("lambda=", round(mod$lam, 3)))

rec=recval_mosp.ss
mod <- bigmatrix(PARAMS)
hist(mosp_sizes[mosp_sizes > y[II][1]], breaks=bin_size, freq=FALSE,main=paste0("MOSP: W SumSq; rec = ",round(recval_mosp.ss,4)))
lines(y[II], mod$w[II] / sum(mod$w[II]) / delta_size)
text(4, .25, paste0("lambda=", round(mod$lam, 3)))

rec=recval_mosp.ll
mod <- bigmatrix(PARAMS)
png(filename = "Figures/StableSizeDistTuning_MOSP.png")
hist(mosp_sizes[mosp_sizes > y[II][1]], breaks=bin_size, freq=FALSE,main=paste0("MOSP: W LogLik; rec = ",round(recval_mosp.ll,4)))
lines(y[II], mod$w[II] / sum(mod$w[II]) / delta_size)
text(4, .25, paste0("lambda=", round(mod$lam, 3)))
dev.off()


# LOG_LIKEHOOD PROFILE, CIs ARE MIN + 1.92
ll.rec <- seq(0.002, 0.006, 0.00001)
ll.profile <- sapply(ll.rec, rec.ll)
rec <- optim(0.05, rec.ll)$par
plot(ll.rec, ll.profile, type="l")
abline(v=rec, lty=2)
abline(h=min(ll.profile) + 1.92)




```

```{r CalculatingLamsSensElas,}
# Run this chunk to calculate the lambdas and the elas/sens for all years/all sites and each site-interval
######
######

POCS_lam <- c()
POSP_lam <- c()
MOSP_lam <- c()

# Change this to save the files as a new name, so they do not overwrite anything
Name <- Scenario

for (i in 1:nrow(POCS)){ 
  MP_POCS <- list(rec = recvalpc, 
                  g.int = POCS$g.int[i], 
                  g.slp = POCS$g.slp[i], 
                  g.var = POCS$g.var[i], 
                  s.int = POCS$s.int[i], 
                  s.slp = POCS$s.slp[i])
  rec=MP_POCS$rec
  pocs        <- bigmatrix(MP_POCS)
  POCS_lam[i] <- pocs$lam
  K <- pocs$K
  Sens<- pocs$sens
  Elas <- pocs$elas
  sdf <- pocs$v.dot.w
  #write.csv(K, sprintf("data/Kernels/%s_Kernel_POCS_%s_%s.csv", 
  #Name,POCS$Sites[i], POCS$Years[i]))
  #write.csv(Sens, sprintf("data/Sens/%s_Sens_POCS_%s_%s.csv", 
  #Name,POCS$Sites[i], POCS$Years[i]))
  #write.csv(Elas, sprintf("data/Elas/%s_Elas_POCS_%s_%s.csv", 
  #Name,POCS$Sites[i], POCS$Years[i]))
}
L_POCS <- data.frame(Sites = POCS$Sites, Years = POCS$Years, 
                     Genus_Code = POCS$Genus_Code, Lambdas = POCS_lam)


for (i in 1:nrow(POSP)){
  MP_POSP <- list(rec = recvalpp, 
                  g.int = POSP$g.int[i], 
                  g.slp = POSP$g.slp[i], 
                  g.var = POSP$g.var[i], 
                  s.int = POSP$s.int[i], 
                  s.slp = POSP$s.slp[i])
  rec=MP_POSP$rec
  posp        <- bigmatrix(MP_POSP)
  POSP_lam[i] <- posp$lam
  K    <- posp$K
  Sens <- posp$sens
  Elas <- posp$elas
  # write.csv(K, sprintf("data/Kernels/%s_Kernel_POSP_%s_%s.csv", 
  #                      Name,POSP$Sites[i], POSP$Years[i]))
  # write.csv(Sens, sprintf("data/Sens/%s_Sens_POSP_%s_%s.csv", 
  #                         Name,POSP$Sites[i], POSP$Years[i]))
  # write.csv(Elas, sprintf("data/Elas/%s_Elas_POSP_%s_%s.csv", 
  #                         Name,POSP$Sites[i], POSP$Years[i]))      
}
L_POSP <- data.frame(Sites = POSP$Sites, Years = POSP$Years, 
                     Genus_Code = POSP$Genus_Code, Lambdas = POSP_lam)

for (i in 1:nrow(MOSP)){
  MP_MOSP <- list(rec = recvalmp, 
                  g.int = MOSP$g.int[i], 
                  g.slp = MOSP$g.slp[i], 
                  g.var = MOSP$g.var[i], 
                  s.int = MOSP$s.int[i], 
                  s.slp = MOSP$s.slp[i])
  
  rec=MP_MOSP$rec
  mosp        <- bigmatrix(MP_MOSP)
  MOSP_lam[i] <- mosp$lam
  K    <- mosp$K
  Sens <- mosp$sens
  Elas <- mosp$elas
  # write.csv(K, sprintf("data/Kernels/%s_Kernel_ MOSP_%s_%s.csv", 
  #                       Name,MOSP$Sites[i],  MOSP$Years[i]))
  # write.csv(Sens, sprintf("data/Sens/%s_Sens_ MOSP_%s_%s.csv", 
  #                          Name,MOSP$Sites[i],  MOSP$Years[i]))
  # write.csv(Elas, sprintf("data/Elas/%s_Elas_MOSP_%s_%s.csv", 
  #                          Name,MOSP$Sites[i],  MOSP$Years[i]))
}
L_MOSP <- data.frame(Sites = MOSP$Sites, Years = MOSP$Years, 
                     Genus_Code = MOSP$Genus_Code, Lambdas = MOSP_lam)

Lambdas <- rbind(L_POCS, L_POSP, L_MOSP)
#save(Lambdas, file = sprintf("data/%s_all_Lambdas.rdata",Name))

```

#Plot IPM results
```{r PlottingIPMresults,}
#plot growth kernel
#image(y,y,t(Growth_kernel), main='growth kernel')
#abline(0,1,lwd=3)	# plot 1:1, which represents stasis

#plot survival kernel
#plot(y,Survival_kernel,type = 'l', main = 'Survival' )
#this looks kinda weird...shouldn't it be more logistic reg shaped?

Name <- Scenario

#Plot full kernel
y_a <- 2*(sqrt(10^y/pi))
#####################################################################
#POCS
#####################################################################
#PLOT growth kernel

##Growth KERNEL
png(filename = paste0("figs/",Name,"_POCS_GrowthK.png"))
image(y, y, t(pocs$Gk)^.1, main="Pocillopora Growth Kernel",
      xlab="Colony Area T (cm^2)",ylab="Colony Area T+1 (cm^2)",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
#title(GeneraNames[1], line=-1)
abline(0, 1, lty=2,lwd=3,col="black")
legend("topleft", bty = "n", lty = c(0,0,2), col = 1,
       legend= c(sprintf("recruitment value = %.2f", recvalpc),
                 sprintf("lambda = %.2f",round(pocs$lam,2)),
                 "1:1 line"))
dev.off()

##Surival KERNEL
png(filename = paste0("figs/",Name,"_POCS_SurvK.png"))
plot(y, pocs$Sk, main="Pocillopora Survivorship",type="l",
     xlab="Colony Area T (cm^2)",ylab="Prob. of Survival",ylim=c(0,1),xaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
#title(GeneraNames[1], line=-1)
#abline(0, 1, lty=2)
legend("topleft", bty = "n", lty = c(0,0), col = 1,
       legend= c(sprintf("recruitment value = %.2f", recvalpc),
                 sprintf("lambda = %.2f",round(pocs$lam,2))))
dev.off()

##Growth + Survivorship KERNEL
png(filename = paste0("figs/",Name,"_POCS_PK.png"))
image(y, y, t(pocs$Pk)^.1, main="Pocillopora Growth & Survivorship Kernel",
      xlab="Colony Area T (cm^2)",ylab="Colony Area T+1 (cm^2)",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
#title(GeneraNames[1], line=-1)
abline(0, 1, lty=2,lwd=3,col="black")
legend("topleft", bty = "n", lty = c(0,0,2), col = 1,
       legend= c(sprintf("recruitment value = %.2f", recvalpc), sprintf("lambda = %.2f",  
                                                                        round(pocs$lam,2)), "1:1 line"))
dev.off()

##FULL KERNEL
png(filename = paste0("figs/",Name,"_POCS_fullK.png"))
image(y, y, t(pocs$K)^.1, main="Pocillopora Full IPM Kernel",
      xlab="Colony Area T (cm^2)",ylab="Colony Area T+1 (cm^2)",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
#title(GeneraNames[1], line=-1)
abline(0, 1, lty=2,lwd=3,col="black")
legend("topleft", bty = "n", lty = c(0,0,2), col = 1,
       legend= c(sprintf("recruitment value = %.2f", recvalpc), sprintf("lambda = %.2f",  
                                                                        round(pocs$lam,2)), "1:1 line"))
dev.off()
# 
# #Another way to plot full kernel
# png(filename = paste0("figs/",Name,"_POCS_alternatefullK.png"))
# image(y, y, t(pocs$K)^.1, xlab="Size (t)",ylab="Size (t+1)",col=topo.colors(100), main="Pocillopora Kernel")
# contour(y,y,t(pocs$K)^.1, add = TRUE, drawlabels = TRUE )
# legend("bottomright", bty = "n", lty = c(0,0,2), col = 1,
#        legend= c(sprintf("recruitment value = %.2f", recvalmp), sprintf("lambda = %.2f",  
#                          round(pocs$lam,2)), "1:1 line"))
# dev.off()


#Plot Elasticity
png(filename = paste0("figs/",Name,"_POCS_elasticity.png"))
#toggle having or dropping the I y[] --> y[I],pocs$elas[,]-->pocs$elas[I,]
image(y,y[],t(pocs$elas[,])^0.2, xlab="Size (t)",ylab="Size (t+1)",main="Pocillopora Elasticity",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000")) #[I] cuts out recruitment
abline(0,1,lwd=3,lty=2)	# plot 1:1
dev.off()

#Plot Sensitivity
png(filename = paste0("figs/",Name,"_POCS_sensitivity.png"))
image(y,y,t(pocs$sens)^0.2, xlab="Size (t)",ylab="Size (t+1)", main="Pocillopora Sensitivity",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
abline(0,1,lwd=3,lty=2)	# plot 1:1
dev.off()


#####################################################################
#POSP
#####################################################################
##Growth KERNEL
png(filename = paste0("figs/",Name,"_POSP_GrowthK.png"))
image(y, y, t(posp$Gk)^.1, main="Porites Growth Kernel",
      xlab="Colony Area T (cm^2)",ylab="Colony Area T+1 (cm^2)",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
#title(GeneraNames[1], line=-1)
abline(0, 1, lty=2,lwd=3)
legend("topleft", bty = "n", lty = c(0,0,2), col = 1,
       legend= c(sprintf("recruitment value = %.2f", recvalpp),
                 sprintf("lambda = %.2f",round(posp$lam,2)),
                 "1:1 line"))
dev.off()

##Surival KERNEL
png(filename = paste0("figs/",Name,"_POSP_SurvK.png"))
plot(y, posp$Sk, main="Porites Survivorship",type="l",
     xlab="Colony Area T (cm^2)",ylab="Prob. of Survival",ylim=c(0,1),xaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
#title(GeneraNames[1], line=-1)
#abline(0, 1, lty=2)
legend("topleft", bty = "n", lty = c(0,0), col = 1,
       legend= c(sprintf("recruitment value = %.2f", recvalpp),
                 sprintf("lambda = %.2f",round(posp$lam,2))))
dev.off()

##Growth + Survivorship KERNEL
png(filename = paste0("figs/",Name,"_POSP_PK.png"))
image(y, y, t(posp$Pk)^.1, main="Porites Growth & Survivorship Kernel",
      xlab="Colony Area T (cm^2)",ylab="Colony Area T+1 (cm^2)",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
#title(GeneraNames[1], line=-1)
abline(0, 1, lty=2,lwd=3)
legend("topleft", bty = "n", lty = c(0,0,2), col = 1,
       legend= c(sprintf("recruitment value = %.2f", recvalpp),
                 sprintf("lambda = %.2f",round(posp$lam,2)),
                 "1:1 line"))
dev.off()

##FULL KERNEL
png(filename = paste0("figs/",Name,"_POSP_fullK.png"))
image(y, y, t(posp$K)^.1,main="Porites Full IPM Kernel",
      xlab="Colony Area T (cm^2)",ylab="Colony Area T+1 (cm^2)",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
#title(GeneraNames[2], line=-1)
abline(0, 1, lty=2,lwd=3)
legend("topleft", bty = "n", lty = c(0,0,2), col = 1,
       legend= c(sprintf("recruitment value = %.2f", recvalpp), sprintf("lambda = %.2f",  round(posp$lam,2)), "1:1 line"))
dev.off()
# 
# #Another way to plot full kernel
# png(filename = paste0("figs/",Name,"_POSP_alternatefullK.png"))
# image(y, y, t(posp$K)^.1, xlab="Size (t)",ylab="Size (t+1)",col=topo.colors(100), main="Porites Kernel")
# contour(y,y,t(posp$K)^.1, add = TRUE, drawlabels = TRUE )
# legend("bottomright", bty = "n", lty = c(0,0,2), col = 1,
#        legend= c(sprintf("recruitment value = %.2f", recvalmp), sprintf("lambda = %.2f",  
#                          round(posp$lam,2)), "1:1 line"))
# dev.off()

#Plot Elasticity
png(filename = paste0("figs/",Name,"_POSP_elasticity.png"))
#toggle having or dropping the I y[] --> y[I],pocs$elas[,]-->pocs$elas[I,]
image(y,y[],t(posp$elas[,])^0.2, xlab="Size (t)",ylab="Size (t+1)",main="Porites Elasticity",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000")) #[I] cuts out recruitment
abline(0,1,lwd=3)	# plot 1:1
dev.off()

#Plot Sensitivity
png(filename = paste0("figs/",Name,"_POSP_sensitivity.png"))
image(y,y,t(posp$sens)^0.2, xlab="Size (t)",ylab="Size (t+1)", main="Porites Sensitivity",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
abline(0,1,lwd=3,lty=2)	# plot 1:1
dev.off()


#####################################################################
#MOSP
#####################################################################
##Growth KERNEL
png(filename = paste0("figs/",Name,"_MOSP_GrowthK.png"))
image(y, y, t(mosp$Gk)^.1, main="Montipora Growth Kernel",
      xlab="Colony Area T (cm^2)",ylab="Colony Area T+1 (cm^2)",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
#title(GeneraNames[1], line=-1)
abline(0, 1, lty=2,lwd=3)
legend("topleft", bty = "n", lty = c(0,0,2), col = 1,
       legend= c(sprintf("recruitment value = %.2f", recvalmp),
                 sprintf("lambda = %.2f",round(mosp$lam,2)),
                 "1:1 line"))
dev.off()

##Surival KERNEL
png(filename = paste0("figs/",Name,"_MOSP_SurvK.png"))
plot(y, mosp$Sk, main="Montipora Survivorship",type="l",
     xlab="Colony Area T (cm^2)",ylab="Prob. of Survival",ylim=c(0,1),xaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
#title(GeneraNames[1], line=-1)
#abline(0, 1, lty=2)
legend("topleft", bty = "n", lty = c(0,0), col = 1,
       legend= c(sprintf("recruitment value = %.2f", recvalmp),
                 sprintf("lambda = %.2f",round(mosp$lam,2))))
dev.off()

##Growth + Survivorship KERNEL
png(filename = paste0("figs/",Name,"_MOSP_PK.png"))
image(y, y, t(mosp$Pk)^.1, main="Montipora Growth & Survivorship Kernel",
      xlab="Colony Area T (cm^2)",ylab="Colony Area T+1 (cm^2)",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
#title(GeneraNames[1], line=-1)
abline(0, 1, lty=2,lwd=3)
legend("topleft", bty = "n", lty = c(0,0,2), col = 1,
       legend= c(sprintf("recruitment value = %.2f", recvalmp),
                 sprintf("lambda = %.2f",round(mosp$lam,2)),
                 "1:1 line"))
dev.off()

##FULL KERNEL
png(filename = paste0("figs/",Name,"_MOSP_fullK.png"))
image(y, y, t(mosp$K)^.1,main="Montipora Full IPM Kernel",
      xlab="Colony Area T (cm^2)",ylab="Colony Area T+1 (cm^2)",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
#title(GeneraNames[2], line=-1)
abline(0, 1, lty=2,lwd=3)
legend("topleft", bty = "n", lty = c(0,0,2), col = 1,
       legend= c(sprintf("recruitment value = %.2f", recvalmp), sprintf("lambda = %.2f",  
                                                                        round(mosp$lam,2)), "1:1 line"))
dev.off()
# 
# #Another way to plot full kernel
# png(filename = paste0("figs/",Name,"_MOSP_alternatefullK.png"))
# image(y, y, t(mosp$K)^.1, xlab="Size (t)",ylab="Size (t+1)",col=topo.colors(100), main="Montipora Kernel")
# contour(y,y,t(mosp$K)^.1, add = TRUE, drawlabels = TRUE )
# legend("bottomright", bty = "n", lty = c(0,0,2), col = 1,
#        legend= c(sprintf("recruitment value = %.2f", recvalmp), sprintf("lambda = %.2f",  
#                          round(mosp$lam,2)), "1:1 line"))
# dev.off()

#Plot Elasticity
png(filename = paste0("figs/",Name,"_MOSP_elasticity.png"))
#toggle having or dropping the I y[] --> y[I],pocs$elas[,]-->pocs$elas[I,]
image(y,y[],t(mosp$elas[,])^0.2, xlab="Size (t)",ylab="Size (t+1)",main="Montipora Elasticity",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000")) #[I] cuts out recruitment
abline(0,1,lwd=3)	# plot 1:1
dev.off()

#Plot Sensitivity
png(filename = paste0("figs/",Name,"_MOSP_sensitivity.png"))
image(y,y,t(mosp$sens)^0.2, xlab="Size (t)",ylab="Size (t+1)", main="Montipora Sensitivity",xaxt="n",yaxt="n")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
axis(2, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
abline(0,1,lwd=3,lty=2)	# plot 1:1
dev.off()


##All Three Survival KERNEL
png(filename = paste0("figs/",Name,"_POCS_SurvK.png"))
plot(y, posp$Sk, main="Three Taxa Comparasion: Survivorship",type="l",
     xlab="Colony Area T (cm^2)",ylab="Prob. of Survival",ylim=c(0,1),xaxt="n",col="darkgreen")
points(y, mosp$Sk,type="l",col="darkblue")
points(y, pocs$Sk,type="l",col="darkred")
axis(1, at = seq(0, 5, 1), labels = c("1","10","100","1,000","10,000","100,000"))
#title(GeneraNames[1], line=-1)
#abline(0, 1, lty=2)
legend("topleft", bty = "n", lty = c(0,0), col = 1,
       legend= c(sprintf("recruitment value = %.2f", recvalpc),
                 sprintf("lambda = %.2f",round(pocs$lam,2))))
dev.off()



#Plot stable size distribution
#png(filename = "figs/AllInt_MOSP_stablesizedist.png")
plot(y, mosp$w,xlab="Size",type="l",main="MOSP Stable size distribution")
subset(ColonyLevel$Genus_Code=="MOSP")#dev.off()

#Plot left eigenvector (reproductive value)
#plot(y,reprodvalue,xlab="Size",type="l",main="Reproductive values")



library(gridExtra)
png("Figures/VRmodel_Params.png", height = 30*nrow(data), width = 90*ncol(data))
grid.table(data)
dev.off()

```

#Perturbation Analysis
```{r PerturbationAnalysis, }
#Assessing the sensitivity of each component model parameter individually, by adjusting each coefficient 
# by +/-1%, and see how it affect the population growth rate (lambda)

#change parameter list to dataframe
df_MP_POSP <- ldply(MP_POSP, data.frame)
modparam_POSP <- spread(df_MP_POSP, key = .id, value = X..i.. )
df_MP_POCS <- ldply(MP_POCS, data.frame)
modparam_POCS <- spread(df_MP_POCS, key = .id, value = X..i.. )
df_MP_MOSP <- ldply(MP_MOSP, data.frame)
modparam_MOSP <- spread(df_MP_MOSP, key = .id, value = X..i.. )



ChangeMe <- modparam_POSP #!!!!!

nparams <- length(ChangeMe) #total number of component model parameters
lam.sn <- matrix(ncol = nparams, nrow = 2, data = NA)  #matrix where every row
all.params.orig <- ChangeMe

for (p in 1:nparams) { #tweak each parameter in turn
  for (j in 1:2) {     #first down by 1% and then 1% up
    all.params <- all.params.orig
    all.params[p] <- all.params[p]*(1+2*(j-1.5)/100)
    BG <- bigmatrix(all.params)
    lam.sn[j,p] <-BG$lam
  }
}
lam.sn #top row is decr by 1%, bottom row is incr

#POSP
normPOSP <- matrix(posp$lam, nrow = 2, ncol = 6)
(round((normPOSP -lam.sn)/posp$lam, 3)) *100

#POCS
normPOCS <- matrix(pocs$lam, nrow = 2, ncol = 6)
(round((normPOCS - lam.sn)/pocs$lam, 3)) *100

#MOSP
normMOSP <- matrix(mosp$lam, nrow = 2, ncol = 6)
(round((normMOSP -lam.sn)/posp$lam, 3)) *100


# perturb manually for -0.1 and then +0.1:
all.params <- all.params.orig
all.params[10] <- -0.01
growth2 <- delta_size * outer(y, y, growth_function, g.int=POSP$g.int[1],   #growth kernel
                              g.slp=POSP$g.slp[1], g.var=POSP$g.var[1])
survival2 <- survival_function(y, s.int=POSP$s.int[1], s.slp=POSP$s.slp[1])     #survival kernel
P2 <- Growth_kernel    #placeholder
z <- 1:n
P2[,z] <- Growth_kernel[,z]*Survival_kernel[z]    #growth/survival kernel
# P2 <- growth2 * survival2
# for (z in 1:n) {
#   P2[,z] <- growth2[,z]*survival2[z]
#   }
Repro2 <- delta_size * outer(y, y, reproduction_function_josh)    #reproduction kernel
K2 <- P2 + Repro2
lam_new <- Re(eigen(K2)$values[1])
lam.sn[21] <- lam_new

```




The next chunk is for the plots Tom made
```{r TomsPlots,}
Name=Scenario
load(file = sprintf("data/%s_all_Lambdas.rdata",Name))

AllD=merge(data,Lambdas)
AllD$AY=c(T,T,T,rep(F,nrow(AllD)-3))
AllD$Island=substr(AllD$Sites,1,3)
names(AllD)[which(names(AllD)=="AIC")]=c("g.AIC","s.AIC")
AllD$Sites=factor(AllD$Sites,levels=
                    sort(unique(AllD$Sites))[c(1,9,16,2,3,14,15,10:13,4:8)])
AllD$Years=factor(AllD$Years,levels=
                    sort(unique(AllD$Years)))
AllD$EndYear=2000+as.numeric(substr(AllD$Years,4,5))
AllD$EndYear[AllD$Years=="All Years"&AllD$Genus_Code=="POSP"]=max(AllD$EndYear[AllD$Genus_Code=="POSP"],na.rm=T)+.5
AllD$EndYear[AllD$Years=="All Years"&AllD$Genus_Code=="POCS"]=max(AllD$EndYear[AllD$Genus_Code=="POCS"],na.rm=T)+.5
AllD$EndYear[AllD$Years=="All Years"&AllD$Genus_Code=="MOSP"]=max(AllD$EndYear[AllD$Genus_Code=="MOSP"],na.rm=T)+.5
AllD$StartYear=2000+as.numeric(substr(AllD$Years,1,2))
AllD$StartYear[AllD$Years=="All Years"&AllD$Genus_Code=="POSP"]=min(AllD$StartYear[AllD$Genus_Code=="POSP"],na.rm=T)-.5
AllD$StartYear[AllD$Years=="All Years"&AllD$Genus_Code=="POCS"]=min(AllD$StartYear[AllD$Genus_Code=="POCS"],na.rm=T)-.5
AllD$StartYear[AllD$Years=="All Years"&AllD$Genus_Code=="MOSP"]=min(AllD$StartYear[AllD$Genus_Code=="MOSP"],na.rm=T)-.5
AllD$Island=factor(AllD$Island,levels=c("All","HAW","MAI","OAH","FFS","KUR"))
GeneraLU=c("Porites sp.","Montipora sp.","Pocillopora sp.")
names(GeneraLU)=c("POSP","MOSP","POCS")
AllD$Genus=GeneraLU[AllD$Genus_Code]
AllD$Genus=factor(AllD$Genus,levels=GeneraLU)
#subset(AllD,Island%in%c("All","HAW","MAI","OAH"))
mycolors <- colorRampPalette(brewer.pal(8, "Set1"))(length(unique(AllD$Sites)))
tobelog2Breaks=c(.5,.75,1,1.5,2,3)#seq(.25,3.5,by=.25)
log2Breaks=log2(tobelog2Breaks)
LambdaBySite=ggplot(subset(AllD,Sites!="All Sites"),aes(x=EndYear,y=log2(Lambdas),size=GModel.n,fill=log2(Lambdas)))+
  geom_segment(aes(xend=StartYear,yend=log2(Lambdas)),alpha=.5,size=1.5)+
  geom_path(color="gray50",lty=2,size=1)+
  geom_point(aes(shape=Island),color="black")+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 2014.75,color="orange")+
  geom_vline(xintercept = 2015.75,color="red")+
  geom_vline(xintercept = 2019.75,color="orange")+
  facet_wrap(Genus~Sites,ncol=7)+
  scale_color_manual(name="Site",values = mycolors)+
  scale_fill_gradient2(name="Lambda",midpoint = 0,breaks = log2Breaks,labels = tobelog2Breaks)+
  scale_size_binned(name="N Colonies",trans = "log10")+
  scale_y_continuous(breaks = log2Breaks,labels = tobelog2Breaks,name="Lambda - Const. Region Recruitment")+
  scale_shape_manual(name="Island",values = c(20:25))+
  theme_bw()+theme(legend.position = "bottom")
LambdaBySite
ggsave(filename = "./figs/LambdasBySitePlots.jpg",plot = LambdaBySite,width=16,height=9)

LambdaByIsland=ggplot(AllD,aes(x=EndYear,y=log2(Lambdas),size=GModel.n,fill=log2(Lambdas)))+
  geom_segment(aes(xend=StartYear,yend=log2(Lambdas)),alpha=.5,size=1.5)+
  geom_path(aes(color=Sites),size=1)+
  geom_point(aes(shape=Island),color="black")+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 2014.75,color="orange")+
  geom_vline(xintercept = 2015.75,color="red")+
  geom_vline(xintercept = 2019.75,color="orange")+
  facet_grid(Island~Genus)+
  scale_color_manual(name="Site",values = mycolors)+
  scale_fill_gradient2(name="Lambda",midpoint = 0,breaks = log2Breaks,labels = tobelog2Breaks)+
  scale_size_binned(name="N Colonies",trans = "log10")+
  scale_y_continuous(breaks = log2Breaks,labels = tobelog2Breaks,name="Lambda - Const. Region Recruitment")+
  scale_shape_manual(name="Island",values = c(20:25))+
  theme_bw()
LambdaByIsland
ggsave(filename = "./figs/LambdaByIslandPlots.jpg",plot = LambdaByIsland,width=8,height=8)


LambdaAll=ggplot(AllD,aes(x=EndYear,y=log2(Lambdas),size=GModel.n,fill=log2(Lambdas)))+
  geom_segment(aes(xend=StartYear,yend=log2(Lambdas)),alpha=.5,size=1.5)+
  #geom_path(aes(color=Sites),size=1)+
  geom_point(aes(shape=Island),color="black")+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 2014.75,color="orange")+
  geom_vline(xintercept = 2015.75,color="red")+
  geom_vline(xintercept = 2019.75,color="orange")+
  facet_grid(.~Genus)+
  scale_color_manual(name="Site",values = mycolors)+
  scale_fill_gradient2(name="Lambda",midpoint = 0,breaks = log2Breaks,labels = tobelog2Breaks)+
  scale_size_binned(name="N Colonies",trans = "log10")+
  scale_y_continuous(breaks = log2Breaks,labels = tobelog2Breaks,name="Lambda - Const. Region Recruitment")+
  scale_shape_manual(name="Island",values = c(20:25))+
  theme_bw()
LambdaAll
ggsave(filename = "./figs/LambdasAllPlots.jpg",plot = LambdaAll,width=12,height=6)

names(AllD)
demo=AllD[,c("Island","Sites","Years","StartYear","EndYear","Genus","GModel.n","g.int","g.slp","g.var","s.int","s.slp","Lambdas")]
demo_num=demo[,8:12]

library(vegan)
library(ggfortify)
pca_res <- prcomp(demo_num, scale = TRUE)
demo=cbind(demo,pca_res$x)
sc=4
arrow_pca=as.data.frame(pca_res$rotation)
arrow_pca$name=row.names(arrow_pca)
hc=hclust(dist(demo_num))

h2k=function(hc,hrange){
  h2k_out=data.frame(h=hrange,k=NA)
  for(i in 1:length(hrange)){
    h2k_out$k[i]=length(unique(cutree(hc,h=hrange[i])))
  }
  return(h2k_out)
}
hr=seq(0,40,by=.1)
k=h2k(hc,hr)
sort(table(k$k),decreasing = T)

ID=cutree(hc,k = 4)
demo$ClustID=factor(ID)
plot(hc)
abline(h = 4.5,col="red")
demo$AY=demo$Years=="All Years"
ggplot(demo,aes(x=PC2,y=PC3))+
  geom_segment(aes(x = 0,xend=sc*PC2,y=0,yend=sc*PC3),data=arrow_pca,color="gray50")+
  geom_text(aes(x=sc*PC2,y=sc*PC3,label=name),data=arrow_pca,color="gray50")+
  geom_point(data=subset(demo,AY==T),aes(color=Genus),size=5,pch=1)+
  geom_text(aes(shape=ClustID,color=Genus,label=ClustID,size=Lambdas))+
  scale_shape_manual(values=1:15)+
  scale_color_discrete()+
  theme_bw()+facet_grid("Genus")

plot(log10(demo$Lambdas)~demo$ClustID)
abline(h=0)

library(scales)
ggplot(AllD,aes(group=Genus_Code))+
  geom_hline(yintercept = c(14.75),size=3,color="gold")+
  geom_hline(yintercept = c(15.75),size=3,color="red")+
  geom_hline(yintercept = c(19.75),size=3,color="orange")+
  geom_linerange(aes(ymin=StartYear,ymax=EndYear,x=Sites,color=log2(Lambdas),size=log2(Lambdas)),
                 position=position_dodge(width=.5),alpha=1)+#,data=subset(AllD,Genus_Code=="POCS"))+
  geom_point(aes(shape=Genus_Code,y=StartYear,x=Sites),fill="black",size=2,position=position_dodge(width=.5),color="black",alpha=1)+#,data=subset(AllD,Genus_Code=="POCS"))+
  geom_point(aes(shape=Genus_Code,y=EndYear,x=Sites,size=log2(Lambdas),fill=log2(Lambdas)),position=position_dodge(width=.5),color="black",alpha=1)+
  geom_vline(xintercept = c(1.5,2.5,3.5,5.5,7.5,11.5))+
  scale_fill_distiller(type = "div",name="Lambda",palette = "Spectral",direction = 1,limits = c(-1,1))+
  #scale_fill_gradient2(name="Lambda",mid = "yellow",high="blue",low="red")+
  scale_size_area(name="Lambda")+
  scale_color_distiller(type = "div",name="Lambda",palette = "Spectral",direction = 1,limits = c(-1,1))+
  #scale_color_gradient2(name="Lambda",mid = "yellow",high="blue",low="red")+
  scale_shape_manual(name="Genus",values = c(22,21,23))+
  #  scale_size_area(limits=log2(c(.5,2)),breaks=log2(seq(.5,2,length.out = 5)),labels=seq(.5,2,length.out = 5),oob=squish)+
  coord_equal()+
  coord_flip()+
  theme_bw()+
  theme(axis.text.x = element_text(angle=90,size = 10,hjust = 0),panel.background=element_rect(fill = "white"),panel.grid = element_blank())

ggplot(AllD,aes(group=Genus_Code))+
  geom_hline(yintercept = c(14.75),size=3,color="gold")+
  geom_hline(yintercept = c(15.75),size=3,color="red")+
  geom_hline(yintercept = c(19.75),size=3,color="orange")+
  geom_linerange(aes(ymin=StartYear,ymax=EndYear,x=Sites,color=log2(Lambdas),size=log2(Lambdas)),
                 position=position_dodge(width=.5),alpha=1)+#,data=subset(AllD,Genus_Code=="POCS"))+
  geom_point(aes(shape=Genus_Code,y=StartYear,x=Sites),fill="black",size=2,position=position_dodge(width=.5),color="black",alpha=1)+#,data=subset(AllD,Genus_Code=="POCS"))+
  geom_point(aes(shape=Genus_Code,y=EndYear,x=Sites,size=log2(Lambdas),fill=log2(Lambdas)),position=position_dodge(width=.5),color="black",alpha=1)+
  geom_vline(xintercept = c(1.5,2.5,3.5,5.5,7.5,11.5))+
  scale_fill_distiller(type = "div",name="Lambda",palette = "Spectral",direction = 1,limits = c(-1,1))+
  #scale_fill_gradient2(name="Lambda",mid = "yellow",high="blue",low="red")+
  scale_size_area(name="Lambda")+
  scale_color_distiller(type = "div",name="Lambda",palette = "Spectral",direction = 1,limits = c(-1,1))+
  #scale_color_gradient2(name="Lambda",mid = "yellow",high="blue",low="red")+
  scale_shape_manual(name="Genus",values = c(22,21,23))+
  #  scale_size_area(limits=log2(c(.5,2)),breaks=log2(seq(.5,2,length.out = 5)),labels=seq(.5,2,length.out = 5),oob=squish)+
  coord_equal()+
  coord_flip()+
  theme_bw()+
  theme(axis.text.x = element_text(angle=90,size = 10,hjust = 0),panel.background=element_rect(fill = "white"),panel.grid = element_blank())



ggplot(subset(AllD,Sites=="MAI_SIO_K02"),aes(x=log2(Lambdas)))+
  geom_histogram(aes(fill=R.sqd,color=pR2))+
  geom_vline(aes(xintercept = log2(Lambdas)),color="red",data=subset(AllD,Sites=="All Sites"))+
  facet_grid(.~Genus_Code)+
  theme_bw()



```
Ignore the stuff below!!


```{r LoadData_Subsetting,}
# Loading in the data from analysis.Rmd
load("data/Growth_intmod_params.rdata")
load("data/Survival_intmod_params.rdata")
# load("data/Recruitment_sizeIndependent.rdata")
# load("data/Recruitment_sizeDependent.rdata")
load("data/SiteInterval_Gmodfits.rdata")
load("data/SiteInterval_Smodfits.rdata")

# Separating the growth data frame by genera #
POCS_G_1 <- dt[dt$Genus_Code == "POCS",][1,]
POCS_G_1 <- cbind(POCS_G_1, data.frame(g.var=0.230512176))
a        <- GrowthDataFrame[GrowthDataFrame$Genus_Code == "POCS",]
POCS_G_2 <- a[which(a$g.int >0),1:6]
POCS_G   <- rbind(POCS_G_1, POCS_G_2) 

POSP_G_1   <- dt[dt$Genus_Code == "POSP",][1,]
POSP_G_1 <- cbind(POSP_G_1, data.frame(g.var=0.372585621))
b        <- GrowthDataFrame[GrowthDataFrame$Genus_Code == "POSP",]
POSP_G_2 <- b[which(b$g.int >0),1:6]
POSP_G   <- rbind(POSP_G_1, POSP_G_2) 

MOSP_G_1   <- dt[dt$Genus_Code == "MOSP",][1,]
MOSP_G_1 <- cbind(MOSP_G_1, data.frame(g.var=1.102913776))
c        <- GrowthDataFrame[GrowthDataFrame$Genus_Code == "MOSP",] 
MOSP_G_2 <- c[which(c$g.int >0),1:6]
MOSP_G   <- rbind(MOSP_G_1, MOSP_G_2)

##############
#SURVIVAL
# subsetting the survival data frame by genera 
POCS_S_1 <- dS[dS$Genus_Code == "POCS",][1,]
a        <- SurvivalDataFrame[SurvivalDataFrame$Genus_Code == "POCS",]
POCS_S_2 <- a[which(a$s.int >0),1:5]
POCS_S   <- rbind(POCS_S_1,POCS_S_2)

POSP_S_1 <- dS[dS$Genus_Code == "POSP",][1,]
b        <- SurvivalDataFrame[SurvivalDataFrame$Genus_Code == "POSP",]
POSP_S_2 <- b[which(b$s.int >0),1:5]
POSP_S   <- rbind(POSP_S_1,POSP_S_2)

MOSP_S_1 <- dS[dS$Genus_Code == "MOSP",][1,]
c        <- SurvivalDataFrame[SurvivalDataFrame$Genus_Code == "MOSP",] 
MOSP_S_2 <- c[which(c$s.int >0),1:5]
MOSP_S   <- rbind(MOSP_S_1,MOSP_S_2)


# ##############
# #RECRUITMENT
# POCS_R <- subset(dr, Genus_Code == "POCS")
# POSP_R <- subset(dr, Genus_Code == "POSP")
# MOSP_R <- subset(dr, Genus_Code == "MOSP")
# 
# POCS_Rdep <- subset(dr_size, Genus_Code == "POCS")
# POSP_Rdep <- subset(dr_size, Genus_Code == "POSP")
# MOSP_Rdep <- subset(dr_size, Genus_Code == "MOSP")
# 
# POCS_R <- subset(POCS_R,Years == "All_Years" )
# totrecruits_POCS <- sum(POCS_R$Tots_recs_peryear, na.rm = T)
# mean(POCS_R$Tots_recs_peryear, na.rm = T)
# 
# POSP_R <- subset(POSP_R,Years == "All_Years" )
# totrecruits_POSP <- sum(POSP_R$Tots_recs_peryear, na.rm = T)
# mean(POSP_R$Tots_recs_peryear, na.rm = T)
# 
# MOSP_R <- subset(MOSP_R,Years == "All_Years" )
# totrecruits_MOSP <- sum(MOSP_R$Tots_recs_peryear, na.rm = T)
# mean(MOSP_R$Tots_recs_peryear, na.rm = T)


```






